Updated back to 3gb because 4 gb exceeds the maximum limit https://jenkins.cd.test.fabric8.io/job/fabric8io/job/fabric8/job/master/17/console
Invalid maximum heap size: -Xmx4096m
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.