Updated again because job failed for 2048 also https://jenkins.cd.test.fabric8.io/job/fabric8io/job/fabric8/job/master/16/console
[ERROR] Java heap space -> [Help 1]
java.lang.OutOfMemoryError: Java heap space